### ISSUE TITLE
Strange Behavior in AP6210 integration..

### ISSUE THREAD

**Issue by shinemoon** [EddyBeaupre/ap6210#3]
Hi, Eddy,

Thanks for the driver and which I tried hard to leverage :) , during progress, I eventually can insert the ap6210, but some confusing thing is when mod loaded, and I tried 'sudo ifconfig wlan0 up', after some 'normal log' and then after the firmware & nvram downloaded, I got error ..

> 
cubie@Cubian:~$ sudo ifconfig wlan0 up
[sudo] password for cubie: 
<3>[ap6210] Dongle Host Driver, version 1.28.23.3 (r).
<3>[ap6210] Compiled in drivers/net/wireless/ap6210 on Dec 17 2014 at 20:49:27.
<3>[ap6210] WLAN going back to live
sdio_reset_comm():
<6>[mmc-msg] sdc3 set ios: clk 50000000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<6>[mmc-msg] sdc3 set ios: clk 50000000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<6>[mmc-msg] sdc3 set ios: clk 400000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<6>[mmc-msg] sdc3 set round clock 400000, src 24000000
<6>[mmc-msg] sdc3 set ios: clk 400000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<4>mmc2: queuing unknown CIS tuple 0x80 (2 bytes)
<4>mmc2: queuing unknown CIS tuple 0x80 (3 bytes)
<4>mmc2: queuing unknown CIS tuple 0x80 (3 bytes)
<4>mmc2: queuing unknown CIS tuple 0x80 (7 bytes)
<6>[mmc-msg] sdc3 set ios: clk 400000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<6>[mmc-msg] sdc3 set ios: clk 50000000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<6>[mmc-msg] sdc3 set round clock 43636363, src 480000000
<6>[mmc-msg] sdc3 set ios: clk 50000000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<3>[ap6210] dhd_bus_devreset: WLAN ON
<3>[ap6210] Final fw_path=/lib/firmware/ap6210/fw_bcm40181a2.bin
<3>[ap6210] Final nv_path=/lib/firmware/ap6210/nvram_ap6210.txt
<3>[ap6210] download firmware /lib/firmware/ap6210/fw_bcm40181a2.bin
<3>[ap6210] dhd_bus_devreset: dhd_bus_start fail with -5
<3>[ap6210] dhd_dev_reset: dhd_bus_devreset: -5
<4>[sched_delayed] sched: RT throttling activated
<3>[ap6210] dhdcdc_set_ioctl: dhdcdc_msg failed w/status -5
<3>[ap6210] bcmsdh_sdmmc: F0 Wr:0x04: write disallowed
<3>[ap6210] dhd_bus_devreset: WLAN OFF DONE
<3>[ap6210] WLAN placed in RESET
<3>[ap6210] dhd_open: failed with code -5
SIOCSIFFLAGS: Operation not permitted

But most strange thing is , if I immediately do it again, then it show some OK status like:

> 
cubie@Cubian:~$ sudo ifconfig wlan0 up
<3>[ap6210] Dongle Host Driver, version 1.28.23.3 (r).
<3>[ap6210] Compiled in drivers/net/wireless/ap6210 on Dec 17 2014 at 20:49:27.
<3>[ap6210] WLAN going back to live
sdio_reset_comm():
<6>[mmc-msg] sdc3 set ios: clk 50000000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<6>[mmc-msg] sdc3 set ios: clk 50000000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<6>[mmc-msg] sdc3 set ios: clk 400000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<6>[mmc-msg] sdc3 set round clock 400000, src 24000000
<6>[mmc-msg] sdc3 set ios: clk 400000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<4>mmc2: queuing unknown CIS tuple 0x80 (2 bytes)
<4>mmc2: queuing unknown CIS tuple 0x80 (3 bytes)
<4>mmc2: queuing unknown CIS tuple 0x80 (3 bytes)
<4>mmc2: queuing unknown CIS tuple 0x80 (7 bytes)
<6>[mmc-msg] sdc3 set ios: clk 400000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<6>[mmc-msg] sdc3 set ios: clk 50000000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<6>[mmc-msg] sdc3 set round clock 43636363, src 480000000
<6>[mmc-msg] sdc3 set ios: clk 50000000Hz bm PP pm ON vdd 3.3V width 4 timing SD-HS(SDR25) dt B
<3>[ap6210] dhd_bus_devreset: WLAN ON
<3>[ap6210] Final fw_path=/lib/firmware/ap6210/fw_bcm40181a2.bin
<3>[ap6210] Final nv_path=/lib/firmware/ap6210/nvram_ap6210.txt
<3>[ap6210] download firmware /lib/firmware/ap6210/fw_bcm40181a2.bin
<3>[ap6210] dhd_bus_devreset: WLAN ON DONE
<3>[ap6210] Dongle ready, protocol version 4
<3>[ap6210] Dongle ready, protocol version 4
<3>[ap6210] Firmware up: op_mode=0x0005, Broadcom Dongle Host Driver mac=98:3b:16:de:c6:fe
<3>[ap6210] Firmware version = wl0: Apr 22 2013 14:50:00 version 5.90.195.89.6 FWID 01-b30a427d
<3>[ap6210] Chip: a962 Rev 1 Pkg 9<3>[ap6210] p2p0: p2p_dev_addr=9a:3b:16:de:c6:fe

and I can check as

> 
cubie@Cubian:~$ ifconfig
wlan0     Link encap:Ethernet  HWaddr 98:3b:16:de:c6:fe  
inet6 addr: fe80::9a3b:16ff:fede:c6fe/64 Scope:Link
UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000 
RX bytes:0 (0.0 B)  TX bytes:3107 (3.0 KiB)

but I know there must be something wrong.. and then try to scan and it can't work:

> 
cubie@Cubian:~$ sudo iwlist wlan0 scan
wlan0     Interface doesn't support scanning.

I tried to seek any clues online, but never found similar situation, and do you have any rough idea can guide me some direction? 

Thanks!

BR, Claud

**Comment by EddyBeaupre** [comment]
Sound like a configuration/permission issue, not related to the driver itself.

**Comment by shinemoon** [comment]
Hi Eddy,  

Just revisit topic here, you are right, it eventually solved after cross check code, that I found the WL_HOST_WAKE_DEF_GPIO is hardcoded in dhd_linux.c to be 2, which I once thought can be decided by the apxxxx_host_wake setting in script.bin - [wifi_para] , but I am wrong:), so insert the GPIO 2 setting for the pin again , board running...

But just minor confusion, why here it can't be requested by the wifi_para pin name to make it more flexible instead of such hardcoding GPIO index?..

Thanks,

**Comment by EddyBeaupre** [comment]
Because :)

No seriously, this is just an interim driver for kernel 3.4, since there is official support for it in mainline, there are many things that could be improved in it but i don't want to invest too much in something that will be short lived.

On the other hand if you want to make the necessary changes and submit a patch, you're more than welcome!

**Comment by shinemoon** [comment]
It makes sense;)

But not familiar with the official support you mentioned , do you mean now in official kernal ap6210 has been supported? e.g. for 3.4? I tried bcmdhd from official kernel , but it doesn't work.

And actually I tried your driver in some customized board with a10 , it works well (of course some minor change did for compilation), though later on some a13 based board, it has some strange issue under invesdetigation now -_-//  -- quick question if you can support ... after wl_regon asserted (measured on board), seems the dummy sdio probe has not been called as expected (and no such mmc detection/comunication log as previous behavior in a10 customized board and also cubie truck...), then the down_timeout() reported timeout error...not sure any hint on which direction I should dig into?

And I will try to make some pull request once I make it more clear , maybe some branch for chips besides a20 can help new comer like me in previous months:)

Thanks,

**Comment by EddyBeaupre** [comment]
I mean it is officially supported in thé mainline kernel (the official kernel maintained by Linus Torvald) around 3.15/3.16.

It's been à while since i've playd with this code, so no, i'm not sure where to point, but if i remember well, it's usually the fault of something else playing with SDIO and messing things up before ap6210 get its chance to settle in.

**Comment by shinemoon** [comment]
@EddyBeaupre Thanks, but I am a bit concerned not sure how long time till we can have the sunxi official kernel update to 3.15/16? seems current main trend is still staying in 3.4, right?

And, I also make my own branch based on yours for Sun4i support, just some minor change, and created the pull request hope you can review..

BTW. I am still struggling in A13 case, and I found that seems the fex setting on the wifi_para section, sdio_id setting is just used in the set up checking , and after that seems it is not used any where else... does it mean which sdio port used in this driver actually hardcoded and that might be the reason when I go to A13 board we must use sdio_2 instead of sdio_3 (A13 maximum to sdio 2)....? Do you still rememer where actually define which sdio to be used?

Thanks!

**Comment by EddyBeaupre** [comment]
Mainline is official (Linus's branch), and what works in it is officially supported by Linux-Sunxi, there will never be an official mainline-linux-sunxi branch, since their goal is to merge everything in the official Linux Kernel, Of course there are downside (graphics doesn't work yet, etc...) but AP6210 work out of the box in mainline.

I think it is in ap6210_gpio_wifi.c, but i'm not sure, really been a while since i playd with this and i don't have an A13, only A20 and A10, so i never had to fiddle with it.
